spring:
  profiles:
    active: local

  datasource:
    url: jdbc:mysql://phododo.cbwndlp3bm95.ap-northeast-2.rds.amazonaws.com:3306/phodo
    driverClassName: com.mysql.cj.jdbc.Driver
    username: 'phodo'
    password: 'phodophodo'
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate

swagger:
  url: http://localhost:8080
  desc: for local usages

# JWT token
token:
  secret: phodo-api
  access-token-expiration-time: 900000  # 5분
  refresh-token-expiration-time: 31536000000



---

spring:
  profiles:
    active: real

  datasource:
    url: jdbc:mysql://phododo.cbwndlp3bm95.ap-northeast-2.rds.amazonaws.com:3306/phodo
    driverClassName: com.mysql.cj.jdbc.Driver
    username: 'phodo'
    password: 'phodophodo'
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate

swagger:
  url: http://phododo-env.eba-vn2bdd4z.ap-northeast-2.elasticbeanstalk.com/
  desc: for real usages
  documentation:
    enabled: true


# JWT token
token:
  secret: phodo-api
  access-token-expiration-time: 900000  # 5분
  refresh-token-expiration-time: 31536000000